const RATING_CHANGED = 'RATING_CHANGED';
const COMMENT_ADDED = 'COMMENT_ADDED';
const COMMENT_REMOVED = 'COMMENT_REMOVED';
const MODULE_LOADED = 'MODULE_LOADED';


module.exports = {
    RATING_CHANGED,
    COMMENT_ADDED,
    COMMENT_REMOVED,
    MODULE_LOADED
};
